### ISSUE TITLE
Unable to access Rancher UI

### ISSUE THREAD

**Issue by samavedulark** [clemenko/rke_install_blog#1]
Hi I am unabe to access Rancher UI.
Below is the svc details
cattle-fleet-system   gitjob                                    ClusterIP      X.X.X.X   <none>        80/TCP           56m
cattle-system         rancher                                   ClusterIP      X.X.X.X      <none>        80/TCP,443/TCP   59m
cattle-system         rancher-webhook                           ClusterIP      X.X.X.X    <none>        443/TCP          55m
cattle-system         webhook-service                           ClusterIP      X.X.X.X    <none>        443/TCP          55m
cert-manager          cert-manager                              ClusterIP      X.X.X.X     <none>        9402/TCP         60m
cert-manager          cert-manager-webhook                      ClusterIP      X.X.X.X     <none>        443/TCP          60m
default               kubernetes                                ClusterIP      X.X.X.X       <none>        443/TCP          4d
default               mywebserver-nginx                         LoadBalancer   X.X.X.X     <pending>     80:30282/TCP     3d23h
kube-system           rke2-coredns-rke2-coredns                 ClusterIP      X.X.X.X       <none>        53/UDP,53/TCP    4d
kube-system           rke2-ingress-nginx-controller-admission   ClusterIP      X.X.X.X      <none>        443/TCP          4d
kube-system           rke2-metrics-server                       ClusterIP      X.X.X.X      <none>        443/TCP          4d

Rancher is running succesfully, after that i did 
kubectl port-forward svc/rancher -n cattle-system 30443:443 --address='0.0.0.0'

Still i am not abe to access. I am trying to access Rancher UI from remote machine using IP.

**Comment by clemenko** [comment]
Looks like  you may be missing the ingress or ingress controller. 
What does the following look like?
```bash
kubectl get ingress -A 
```

also did you disable `firewalld` on all the nodes?

**Comment by samavedulark** [comment]
This is the output of kubectl get ingress -A , and i disabled the firewall.
cattle-system   rancher   <none>   bigserver.kube.test   X.X.X.X   80, 443   7h34m

**Comment by clemenko** [comment]
does the DNS for `bigserver.kube.test` point to the ip of the first node?

**Comment by samavedulark** [comment]
No, it is not, we dont have DNS, that's why i wanted to access using IP.

**Comment by clemenko** [comment]
Ah, that is the issue. Using an ingress and controller will use the name to direct the traffic to the service/pod. So without ingress we can create a NodePort Service to give you access.  Run:
```
cat <<EOF | kubectl apply -f -  > /dev/null 2>&1
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rancher
  name: ranchernp
  namespace: cattle-system
spec:
  selector:
    app: rancher
  ports:
  - name: https-internal
    port: 443
    protocol: TCP
  type: NodePort
EOF
```

then check the port number with 

```
kubectl  get svc -A | grep ranchernp
```

you should see `443:30827` or some other 32000 number. Navigate to `https://$YOURIP:32000` to get to the gui. 
hope this helps.

**Comment by clemenko** [comment]
@samavedulark did you ever figure this out?

**Comment by andydford** [comment]
@clemenko It's not good when people do not get back to you!

This worked perfectly for me using the NodePort service.

**Comment by ravisamavedula** [comment]
> @samavedulark did you ever figure this out?

Sorry was away from work and it did work for me, thanks so much

**Comment by clemenko** [comment]
I am going to close this. If it happens again please feel free to reach out!

**Comment by samavedulark** [comment]
>Sorry was away from work and it did work for me, thanks so much
