### ISSUE TITLE
Specify a Unique IP address for the default nginx controller

### ISSUE THREAD

**Issue by voltagebots** [clemenko/rke_install_blog#8]
- is there a way i can specify a public ip address for the nginx controller in an environment where the server is private.

**Comment by clemenko** [comment]
Does the node have public IP address? Are you in AWS where an ELB load balancer is available?

**Comment by voltagebots** [comment]
Thanks for taking out time to respond.
No,  this is an onprem setup.(Vsphere).. I was thinking of a way to assign the public ip to the nginx controller directly but that was dumb of me... Most likley this has to be mapped to the node's private ip...The challenge is, we do not want to expose the node via the internet..an alterante solution is putting it behind a vpn

**Comment by clemenko** [comment]
AH. That is a fun one. There are a few ways to expose Ingress to the internet. You could use a Nat forwarder? or tailscale? https://tailscale.com/kb/1185/kubernetes

**Comment by voltagebots** [comment]
Thank you.
